use crate::parsing::Instruction;

use anyhow::{anyhow, Result};

use std::fs::File;
use std::io::Write;
use std::process::Command;

fn generate_yasm_x86_64_header(file: &mut File) -> Result<()> {
    writeln!(file, "; This file was generated by the Brainfuck compiler")?;
    writeln!(file, "; --- yasm-x86_64-compiler ---")?;
    writeln!(file, "; --- HEADER ---")?;
    writeln!(file, "extern exit")?;
    writeln!(file, "extern putchar")?;
    writeln!(file, "extern getchar")?;
    writeln!(file, "extern printf")?;
    writeln!(file, "segment .data")?;
    writeln!(
        file,
        "\tdebug_pointer: db 10, \"--- DEBUG ---\", 10, \"pointer: %ld\", 10, 0"
    )?;
    writeln!(
        file,
        "\tdebug_memory: db \"memory: %ld\", 10, \"--- DEBUG ---\", 10, 0"
    )?;
    writeln!(file, "overflow_message: db 27, \"[1;31mERROR: overflow exception\", 27, \"[0m\", 10, 0")?;
    writeln!(file, "underflow_message: db 27, \"[1;31mERROR: underflow exeption\", 27, \"[0m\", 10, 0")?;
    writeln!(file, "\tpointer: dd 15000")?;
    writeln!(file, "segment .bss")?;
    writeln!(file, "\tarray: resb 240000")?;
    writeln!(file, "segment .text")?;
    writeln!(file, "\tglobal _start")?;
    writeln!(file, "_start:")?;
    Ok(())
}

fn generate_yasm_x86_64_code(instructions: &[Instruction], file: &mut File) -> Result<()> {
    writeln!(file, "; --- BODY ---")?;
    for (index, instruction) in instructions.iter().enumerate() {
        writeln!(file, "addr_{index}:")?;
        match instruction {
            Instruction::IncrementPointer => {
                writeln!(file, "\t; --- Increment pointer ---")?;
                writeln!(file, "\tmov ebx, [pointer] ; ebx = pointer")?;
                writeln!(file, "\tadd ebx, 1 ; ebx += 1")?;
                writeln!(file, "\tmov [pointer], ebx ; pointer = ebx")?;
                writeln!(file, "\tcmp ebx, 30000")?;
                writeln!(file, "\tjge exception_overflow")?;
            }
            Instruction::DecrementPointer => {
                writeln!(file, "\t; --- Decrement pointer ---")?;
                writeln!(file, "\tmov ebx, [pointer] ; ebx = pointer")?;
                writeln!(file, "\tsub ebx, 1 ; ebx -= 1")?;
                writeln!(file, "\tmov [pointer], ebx ; pointer = ebx")?;
                writeln!(file, "\tcmp ebx, 0")?;
                writeln!(file, "\tjl exception_underflow")?;
            }
            Instruction::Output => {
                writeln!(file, "\t; --- Output ---")?;
                writeln!(file, "\tmov ebx, [pointer] ; ebx = pointer")?;
                writeln!(file, "\tmov edi, [array + ebx * 8] ; edi = array[pointer]")?;
                writeln!(file, "\tcall putchar ; putchar(edi)")?;
            }
            Instruction::Input => {
                writeln!(file, "\t; --- Input ---")?;
                writeln!(file, "\tmov ebx, [pointer] ; ebx = pointer")?;
                writeln!(file, "\tcall getchar ; eax = getchar()")?;
                writeln!(file, "\tmov [array + ebx * 8], eax ; array[pointer] = eax")?;
            }
            Instruction::IncrementValue => {
                writeln!(file, "\t; --- Increment value ---")?;
                writeln!(file, "\tmov ebx, [pointer] ; ebx = pointer")?;
                writeln!(file, "\tmov eax, [array + ebx * 8] ; eax = array[pointer]")?;
                writeln!(file, "\tcmp eax, 255")?;
                writeln!(file, "\tjge .clear")?;
                writeln!(file, "\tadd eax, 1 ; eax += 1")?;
                writeln!(file, "\tmov [array + ebx * 8], eax ; array[pointer] = eax")?;
                writeln!(file, "\tjmp .end")?;
                writeln!(file, ".clear:")?;
                writeln!(file, "\tmov eax, 0; eax = 0")?;
                writeln!(file, "\tmov [array + ebx * 8], eax ; array[pointer] = eax")?;
                writeln!(file, ".end:")?;
            }
            Instruction::DecrementValue => {
                writeln!(file, "\t; --- Decrement value ---")?;
                writeln!(file, "\tmov ebx, [pointer] ; ebx = pointer")?;
                writeln!(file, "\tmov eax, [array + ebx * 8] ; eax = array[pointer]")?;
                writeln!(file, "\tcmp eax, 0")?;
                writeln!(file, "\tjle .clear")?;
                writeln!(file, "\tsub eax, 1 ; eax -= 1")?;
                writeln!(file, "\tmov [array + ebx * 8], eax ; array[pointer] = eax")?;
                writeln!(file, "\tjmp .end")?;
                writeln!(file, ".clear:")?;
                writeln!(file, "\tmov eax, 255; eax = 255")?;
                writeln!(file, "\tmov [array + ebx * 8], eax ; array[pointer] = eax")?;
                writeln!(file, ".end:")?;
            }
            Instruction::LoopStart(target) => {
                writeln!(file, "\t; --- Loop start ---")?;
                writeln!(file, "\tmov ebx, [pointer] ; ebx = pointer")?;
                writeln!(file, "\tmov eax, [array + ebx * 8] ; eax = array[pointer]")?;
                writeln!(file, "\tcmp eax, 0")?;
                writeln!(file, "\tje addr_{target}")?;
            }
            Instruction::LoopEnd(target) => {
                writeln!(file, "\t; --- Loop end ---")?;
                writeln!(file, "\tmov ebx, [pointer] ; ebx = pointer")?;
                writeln!(file, "\tmov eax, [array + ebx * 8] ; eax = array[pointer]")?;
                writeln!(file, "\tcmp eax, 0")?;
                writeln!(file, "\tjne addr_{target}")?;
            }
            Instruction::Debug => {
                writeln!(file, "\t; --- Debug ---")?;
                writeln!(file, "\tlea edi, [debug_pointer]")?;
                writeln!(file, "\tmov esi, ebx")?;
                writeln!(file, "\txor eax, eax")?;
                writeln!(file, "\tcall printf")?;
                writeln!(file, "\txor eax, eax")?;
                writeln!(file, "\tmov ebx, [pointer] ; ebx = pointer")?;
                writeln!(file, "\tmov esi, [array + ebx * 8] ; eax = array[pointer]")?;
                writeln!(file, "\tlea edi, [debug_memory]")?;
                writeln!(file, "\txor eax, eax")?;
                writeln!(file, "\tcall printf")?;
            }
        }
    }
    Ok(())
}

fn generate_yasm_x86_64_footer(file: &mut File) -> Result<()> {
    writeln!(file, "\t; --- EXIT ---")?;
    writeln!(file, "\tmov edi, 0")?;
    writeln!(file, "\tcall exit")?;
    writeln!(file, "exception_overflow:")?;
    writeln!(file, "\tmov edi, overflow_message")?;
    writeln!(file, "\txor eax, eax")?;
    writeln!(file, "\tcall printf")?;
    writeln!(file, "\tmov edi, 1")?;
    writeln!(file, "\tcall exit")?;
    writeln!(file, "exception_underflow:")?;
    writeln!(file, "\tmov edi, underflow_message")?;
    writeln!(file, "\txor eax, eax")?;
    writeln!(file, "\tcall printf")?;
    writeln!(file, "\tmov edi, 1")?;
    writeln!(file, "\tcall exit")?;
    Ok(())
}

pub fn yasm_x86_64_compiler(instructions: &[Instruction]) -> Result<()> {
    let mut file = File::create("/tmp/out.s")?;
    generate_yasm_x86_64_header(&mut file)?;
    generate_yasm_x86_64_code(instructions, &mut file)?;
    generate_yasm_x86_64_footer(&mut file)?;
    let output = Command::new("yasm")
        .args(["-f", "elf64", "-o", "/tmp/out.o", "/tmp/out.s"])
        .output();
    match output {
        Ok(output) => {
            if !output.status.success() {
                return Err(anyhow!(
                    "yasm failed with exit code {}\n{}",
                    output.status.code().unwrap(),
                    String::from_utf8_lossy(&output.stderr)
                ));
            }
            let path = std::env::current_dir()?.join("out");
            let path_str = path.to_str().unwrap();
            let output = Command::new("ld")
                .args([
                    "--dynamic-linker",
                    "/lib64/ld-linux-x86-64.so.2",
                    "-o",
                    path_str,
                    "-lc",
                    "/tmp/out.o",
                ])
                .output();
            match output {
                Ok(output) => {
                    if !output.status.success() {
                        return Err(anyhow!(
                            "ld failed with exit code {}\n{}",
                            output.status.code().unwrap(),
                            String::from_utf8_lossy(&output.stderr)
                        ));
                    }
                }
                Err(error) => return Err(anyhow!("ld failed with error: {}", error)),
            }
            Ok(())
        }
        Err(error) => Err(anyhow!("yasm failed with error: {}", error)),
    }
}
